### ISSUE TITLE
Create Repairs Table & Model

### ISSUE THREAD

**Issue by apoltieva** [Sf-60-Ruby-Cisco/BE-Ruby-Project#27]
As a user, I want to keep track of repairs that were made to my car.

Steps:
1) create repairs table in accordance with our db schema (the amount field should be not null).
2) the amount field should be in cents
3) create Rapair model
4) to the model, add active record validation that would validate numericality of the amount field 

You don't need to add anything to UI, that will be a part of another task.

**Comment by Stoyan83** [comment]
@apoltieva In this issue in the db there is a column invoice, does we have to implement real invoice class in a different table that we will make possible printing documents  or it should be just a text column ?
